{{- define "recipe-service-chart.fullname" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-service-chart.fullname" . }}
  labels:
    app: {{ include "recipe-service-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "recipe-service-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "recipe-service-chart.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: db
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "recipe-service-chart.fullname" . }}-secrets
                  key: db-password
