{{- define "recipe-service-chart.fullname" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name }}
{{- end }}

{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "recipe-service-chart.fullname" . }}
  labels:
    app: {{ include "recipe-service-chart.name" . }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "recipe-service-chart.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
