apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recipe-service-chart.fullname" . }}-secrets
  labels:
    app: {{ include "recipe-service-chart.name" . }}
type: Opaque
data:
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
