replicaCount: 2
image:
  repository: testsdx6
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  hostname: sdx.local-test.de
secrets:
  dbPassword: "postgres"
